# Start with basics of numpy with SAGAR 

In [ ]:
import numpy as np
import time

# Creating array in numpy

In [5]:
arr_1d = np.array([1,2,3,4])
print("1D array : " ,arr_1d)

arr_2d = np.array([[1,2,3] , [4,5,6]])
print("2D array : " ,arr_2d)

1D array :  [1 2 3 4]
2D array :  [[1 2 3]
 [4 5 6]]


### List vs Numpy array

In [15]:
py_list = [1,2,3,4] # Add another list to in the list
print("List by multiply 2 :" , py_list * 2)

# Element wise multiplication
numpy_arr = np.array([1,2,3,4])
print("Numpy array by multiply 2 :" , numpy_arr * 2)


List by multiply 2 : [1, 2, 3, 4, 1, 2, 3, 4]
Numpy array by multiply 2 : [2 4 6 8]


# List vs Numpy array who is efficient

In [14]:


start = time.time()
py_list = [i * 2 for i in range(1000000)]
print("Time taken by manual list in python : " , time.time() - start)

start = time.time()
np_arr = np.arange(1000000) * 2
print("Time taken by numpy list in python : " , time.time() - start)

Time taken by manual list in python :  0.04864501953125
Time taken by numpy list in python :  0.006928920745849609


# Array creation in numpy 

In [9]:
# 1 : Zero
zero_arr = np.zeros((4 , 4))
print("This is zero array zreation method : \n" , zero_arr)

# 2 : ones
one_arr = np.ones((4 , 4))
print("This is one array zreation method : \n" , one_arr)

This is zero array zreation method : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
This is one array zreation method : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
# Other array method for creation 
#  We have a full is defing constant fillups value for rows and colums , option value is constant in parameter 

full = np.full((3 , 4) , 6)  
print("Fill method : \n" , full)

#  random method which is mostly used in numpy it fill value randomly

random = np.random.random((4 , 4)) * 10
print("random method : \n" , random)

#  arange method print value in sequence , it takes optional parameter whhich is for steps how would you like to increase
sequence = np.arange(0 , 20 , 4) 
print("sequence method : \n" , sequence)

Fill method : 
 [[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]
random method : 
 [[2.59772554 7.49207462 0.4197467  5.8607172 ]
 [1.07906878 2.49279001 5.59650371 0.91900775]
 [5.37426933 3.97437075 6.80799138 6.35542139]
 [2.12639656 2.19054202 1.51890217 9.84955503]]
sequence method : 
 [ 0  4  8 12 16]


<!-- Now vector , metrices , tensor -->

In [11]:
# Vector it is a simple array
vector = np.array([1, 2, 3, 4, 5])
print("Vector :" , vector)


# Metrices it is a combination of rows and columns in array
metrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Metrix :" , metrix)

# Tensor it is besically multidimentional array like in one metrix we have other two metrix
tensor = np.array([[[1, 2] , [3, 4]],
                  [[5, 6] , [7, 8]]])
print("Tensor :" , metrix)

Vector : [1 2 3 4 5]
Metrix : [[1 2 3]
 [4 5 6]]
Tensor : [[1 2 3]
 [4 5 6]]


In [12]:
#  numpy array properties ther are lots of properies bu we will explore important methods

metrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Metrix :" , metrix)
 #  1 : shape
print("Shape  : " , metrix.shape)

 #  2 : Dimention
print("Dimention  : " , metrix.ndim)

 #  3 : size
print("Size  : " , metrix.size)

 #  1 : Data type
print("Data type  : " , metrix.dtype)

Metrix : [[1 2 3]
 [4 5 6]]
Shape  :  (2, 3)
Dimention  :  2
Size  :  6
Data type  :  int64


In [13]:
#  Array Reshape
arr = np.arange(10)
print("Sequence array :" , arr)

#  Array Reshape method it take rows and column parameter and conver sequence to metrix
reshape = arr.reshape((2,5))
print("reshape array :" , reshape)

#  Flatten method it convert metrix to seqnence array , and it print copy of reshape metrix
flatten = reshape.flatten()
print("flatten array :" , flatten)

# Ravel method also work like flatten but it print real value in sequence metrix instead of copy vale
ravel = reshape.ravel()
print("ravel array :" , ravel)

#  Transpose method convert order of metrix rows to colums and columns to rows
transpose = reshape.T
print("transpose array :" , transpose)

Sequence array : [0 1 2 3 4 5 6 7 8 9]
reshape array : [[0 1 2 3 4]
 [5 6 7 8 9]]
flatten array : [0 1 2 3 4 5 6 7 8 9]
ravel array : [0 1 2 3 4 5 6 7 8 9]
transpose array : [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
