## Numpy advance operations with example

In [1]:
import numpy as np
from matplotlib import pyplot as plt

Matplotlib is building the font cache; this may take a moment.


In [ ]:
# Sales data from [2022 , 2023 , 2024 , 2025]

sales_data = np.array([
    [1 , 150000 , 180000 , 210000 , 120000], 
    [2 , 160000 , 200000 , 230000 , 250000], 
    [3 , 300000 , 120000 , 180000 , 160000],
])

#  we find shapes
print("Shapes of the sales data :" , sales_data.shape)

# We retrive some data
print("Selected items : " , sales_data[ : , 1 : ])



Shapes of the sales data : (3, 5)
Selected items :  [[150000 180000 210000 120000]
 [160000 200000 230000 250000]
 [300000 120000 180000 160000]]
[203333.33333333 166666.66666667 206666.66666667 176666.66666667]


### Total sales per year

In [24]:
year_total_cost = np.sum(sales_data[ : , 1 : ] , axis=0)
print("Year toatl cost per year :" , year_total_cost)

#  All year total cost
total_cost_all_year = np.sum(sales_data , axis=1)
print("Year toatl cost by all year :" , total_cost_all_year)

#  minimum sales per year
min_sales = np.min(sales_data[ : , 1 : ] , axis=1) # we exclude first index of sales
print(min_sales)

#  maximum sales per year
max_sales = np.max(sales_data[ : , 1 : ] , axis=0) # we exclude first index of sales
print(max_sales)

# Average sales per year
avg_sales = np.mean(sales_data[ : , 1 :] , axis=1)
print(avg_sales)

# Cumulative sum 
cumsum = np.cumsum(sales_data[ : , 1: ] , axis=1)
print(cumsum)

Year toatl cost per year : [610000 500000 620000 530000]
Year toatl cost by all year : [660001 840002 760003]
[120000 160000 120000]
[300000 200000 230000 250000]
[165000. 210000. 190000.]
[[150000 330000 540000 660000]
 [160000 360000 590000 840000]
 [300000 420000 600000 760000]]
